### ISSUE TITLE
Make isotropic RAM error

### ISSUE THREAD

**Issue by pr4deepr** [clij/clijx-assistant#38]
HI Robert
  When clicking "Make Isotropic" on a 3D stack in CLIJ-assistant, it runs out of VRAM even before I get a chance to enter the voxel spacing. Smaller stacks are ok, but with big stacks it is a problem. I can run it fine on CLIJx, so it does fit in the video memory.

Cheers
Pradeep

**Comment by haesleinhuepf** [comment]
Hey Pradeep @pr4deepr,

I think this bug is fixed already, but you may not have received the update yet. Would you please try to deactivate the "clincubator": update site and activate "clijx-assistant" instead? Let me know if the problem goes away then and sorry for not mentioning this earlier.

Cheers,
Robert

**Comment by pr4deepr** [comment]
Hi
   Yes, that was exaactly the issue!!
Thanks. There are a lot more new toys now! :)

Cheers
Pradeep
