### ISSUE TITLE
Imrove auto-generated names of variables in generated scripts

### ISSUE THREAD

**Issue by tischi** [clij/clijx-assistant#50]
I could not find a command to Rename an image.
Can I just use the Rename command in ImageJ? 
But then I guess this not be recorded in the script, or would it?

**Comment by haesleinhuepf** [comment]
Hi @tischi ,

you mean renaming an image in the GPU I guess. I conclude you're using clij from ImageJ macro, because in the other scripting languages, images have no names. Interesting request. Can you explain the use-case for that?

As a workaround, you can [copy](https://clij.github.io/clij2-docs/reference_copy) an image to a given name.

**Comment by haesleinhuepf** [comment]
I [just added](https://github.com/clij/clijx/commit/edd828cfb7123c5d628828a295d4d2e81a2d00bb) a function `pushAs` which has two parameters: The image to push and the name under which it will be accessible on the GPU. Does that help your use-case?

**Comment by tischi** [comment]
>  I conclude you're using clij from ImageJ macro, because in the other scripting languages, images have no names.

Indeed, good point. Maybe my point is a bit more general: in the recorded macros (and scripts?) the images have names `imageN`, which makes it a bit hard to read the scripts. If the image names would correspond to whatever happened in the last processing step, it could be better for human readability, e.g. `gaussianBlurred` or `sumProjected`. Not sure how feasible this is.
