### ISSUE TITLE
Make UI more concise

### ISSUE THREAD

**Issue by tischi** [clij/clijx-assistant#58]
If there are many windows a typical computer screen becomes very full very quickly.

Suggestions:
- Remove white space between UI elements
- Consider removing the `[ >> ]`  double arrows

<img width="575" alt="image" src="https://user-images.githubusercontent.com/2157566/115204809-2e5bc880-a0f9-11eb-8124-e6f7cf322583.png">

I think you could get the same UI elements into this space:

<img width="359" alt="image" src="https://user-images.githubusercontent.com/2157566/115204959-5b0fe000-a0f9-11eb-937b-df1e19e627e4.png">

**Comment by haesleinhuepf** [comment]
Hey @tischi ,

thanks for the great suggestion! I'm afraid this is a Mac-specific issue. On my Windows it looks smaller:
![image](https://user-images.githubusercontent.com/12660498/115363590-e30dec80-a1c2-11eb-9fe3-89a7474af2da.png)

That's why it would be cool if someone with a Mac could tackle this. I would vote against removing buttons, because I use them, but making the buttons smaller and removing the gap between them is a fantastic idea. 

To whoever wants to give it a shot (no pressure Tischi), the code of these button panels lives here:
https://github.com/clij/assistant/blob/master/src/main/java/net/haesleinhuepf/clijx/assistant/AbstractAssistantGUIPlugin.java#L163-L193

Cheers,
Robert

**Comment by tischi** [comment]
I volunteer to tackle it but cannot promise a deadline right now.
